### ISSUE TITLE
Fails to deploy contract to Testnet

### ISSUE THREAD

**Issue by bafu** [thundercore/auction-template#3]
Fails to deploy contract to Testnet.

Considering is it because there is no `contracts/Migrations.sol`

**Steps to Reproduce**

1. Build contract
2. Deploy contract

        $ npx truffle migrate --network thunder-testnet

**Error Logs**

```
$ npx truffle migrate --network thunder-testnet

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'thunder-testnet'
> Network id:      18
> Block gas limit: 100000000 (0x5f5e100)


1_initial_migration.js
======================

/home/bafu/codes/auction-template/node_modules/truffle/build/459.bundled.js:25494
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for Migrations from any sources
    at Resolver.require (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at /home/bafu/codes/auction-template/migrations/1_initial_migration.js:1:30
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.file (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/require/require.js:94:1)
    at Migration._load (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:49:1)
    at Migration.run (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)
Truffle v5.3.1 (core: 5.3.1)
Node v14.16.1
```

**Environment**

```
truffle version
Truffle v5.3.1 (core: 5.3.1)
Solidity - 0.5.17 (solc-js)
Node v14.16.1
Web3.js v1.3.5
```

**Comment by o-p** [comment]
I missed Truffle build-in Migration file. Added in commit 7b30f7b64f489ad5e7cc1dc024fa305503352323

**Comment by bafu** [comment]
Confirmed that the added `Migrations.sol` can fix this issue.
