### ISSUE TITLE
Fails to create an Auction on Testnet

### ISSUE THREAD

**Issue by bafu** [thundercore/auction-template#5]
**Steps to Reproduce**

1. Instantiate AuctionFactory:

        truffle(thunder-testnet)> f = await AuctionFactory.at('0x0Be873FB1F881A7def426b434c2F0879A761871E')

2. Create an Auction.

        truffle(thunder-testnet)> f.createAuction('1618922820', '0.5', '0.1', accounts[0])

**Error Logs**

```
truffle(thunder-testnet)> f.createAuction('1618922820', '0.5', '0.1', accounts[0])                   
Uncaught:                                                                                            Error: invalid BigNumber string (argument="value", value="0.5", code=INVALID_ARGUMENT, version=bignum
ber/5.0.8)                                                                                               at evalmachine.<anonymous>:0:3      
    at sigintHandlersWrap (vm.js:273:12)                                                             
    at Script.runInContext (vm.js:140:14)                                                                at runScript (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/core
/lib/console.js:270:1)      at Console.interpret (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packa
ges/core/lib/console.js:285:1)                                                                       
    at bound (domain.js:413:15)
    at REPLServer.runBound [as eval] (domain.js:424:12)                           
    at REPLServer.onLine (repl.js:817:10)
    at REPLServer.emit (events.js:315:20)
    at REPLServer.EventEmitter.emit (domain.js:467:12)
    at REPLServer.Interface._onLine (readline.js:337:10)
    at REPLServer.Interface._line (readline.js:666:8)
    at REPLServer.Interface._ttyWrite (readline.js:1010:14)
    at REPLServer.self._ttyWrite (repl.js:907:9)
    at ReadStream.onkeypress (readline.js:213:10)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.EventEmitter.emit (domain.js:467:12)
    at emitKeys (internal/readline/utils.js:345:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1144:36) {
  reason: 'invalid BigNumber string',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '0.5',
  hijackedStack: 'Error: invalid BigNumber string (argument="value", value="0.5", code=INVALID_ARGUME
NT, version=bignumber/5.0.8)\n' +
    '    at lib_esm_Logger.makeError (/home/bafu/codes/auction-template/node_modules/truffle/build/we
bpack:/node_modules/web3-eth-abi/node_modules/@ethersproject/logger/lib.esm/index.js:166:1)\n' +
    '    at lib_esm_Logger.throwError (/home/bafu/codes/auction-template/node_modules/truffle/build/w
ebpack:/node_modules/web3-eth-abi/node_modules/@ethersproject/logger/lib.esm/index.js:175:1)\n' +
    '    at lib_esm_Logger.throwArgumentError (/home/bafu/codes/auction-template/node_modules/truffle
/build/webpack:/node_modules/web3-eth-abi/node_modules/@ethersproject/logger/lib.esm/index.js:178:1)\
n' +
    '    at Function.from (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/node
_modules/web3-eth-abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:171:26)\n' +
    '    at NumberCoder.encode (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:
/node_modules/web3-eth-abi/node_modules/@ethersproject/abi/lib.esm/coders/number.js:13:17)\n' +
    '    at /home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/node_modules/web3-e
th-abi/node_modules/@ethersproject/abi/lib.esm/coders/array.js:57:1\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at pack (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/node_modules/
web3-eth-abi/node_modules/@ethersproject/abi/lib.esm/coders/array.js:43:1)\n' +
    '    at TupleCoder.encode (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/
node_modules/web3-eth-abi/node_modules/@ethersproject/abi/lib.esm/coders/tuple.js:19:16)\n' +
    '    at AbiCoder.encode (/home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/no
de_modules/web3-eth-abi/node_modules/@ethersproject/abi/lib.esm/abi-coder.js:82:1)\n' +
    '    at ABICoder.encodeParameters (/home/bafu/codes/auction-template/node_modules/truffle/build/w
ebpack:/node_modules/web3-eth-abi/lib/index.js:121:1)\n' +
    '    at /home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/node_modules/web3-e
th/node_modules/web3-eth-contract/lib/index.js:439:1\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object._encodeMethodABI (/home/bafu/codes/auction-template/node_modules/truffle/build/web
pack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:438:6)\n' +
    '    at /home/bafu/codes/auction-template/node_modules/truffle/build/webpack:/packages/contract/l
ib/execute.js:181:1\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
```

**Comment by bafu** [comment]
This error is expected because the `createAuction` requires both `initialPrice` and `step` to be `uint256`.

This is more like an UX issue, and I open this issue as a record.

**Comment by o-p** [comment]
It only accept integer. We need to scaled the input number by token's decimals.

For example, TT-ETH decimals are 18. If you want to set initial price to 0.5, the input value should be `0.5e18` and cast it to string: `"500000000000000000"`

**Comment by bafu** [comment]
Confirmed with upstream that the unit of `initialPrice` and `step` is Wei instead of TT-ETH. In this case, the UX issue does not exist, and I will close this issue directly.
